### ISSUE TITLE
SharpShooter Baron(!)/Dragon(?) Secure

### ISSUE THREAD

**Issue by between1and1** [xcsoftforlsharp/LeagueSharp#5]
I've tried to secure Baron with Rend (E) in several ranked games but ALL of them failed to do so with the script. Please look into this. I've tried deleting appdata/cleaning registry/reinstalling both client and assembly but nothing has fixed this issue. TY

**Comment by xcsoftforlsharp** [comment]
Thank you for your report. Fixed(Unconfirmed).
